### ISSUE TITLE
Payment Status Discrepancy Between WooCommerce and PayTabs Merchant Dashboard

### ISSUE THREAD

**Issue by cgdmohamed** [paytabscom/paytabs-woocommerce#74] opened 2024-02-18 12:41 UTC
**Issue:**
There is a discrepancy in the payment status between WooCommerce and the PayTabs merchant dashboard. Despite successful payments being reflected in the PayTabs dashboard, orders in WooCommerce are stuck in a "Pending Payment" status.

**Steps to Reproduce:**

- Place an order on the WooCommerce website.
- Complete the payment process using the PayTabs payment gateway.
- Check the payment status in both WooCommerce and the PayTabs merchant dashboard.

**Expected Behavior:**
The payment status in WooCommerce should be updated to "Paid" or equivalent upon successful payment confirmation from the PayTabs gateway.

**Actual Behavior:**
The payment status in WooCommerce remains stuck at "Pending Payment" even after successful payment confirmation from the PayTabs gateway.

**Additional Information:**
The issue has been observed across multiple environments, including WordPress latest version, with PHP 7.4 and PHP 8.0.
Testing has been conducted both with and without IPN in test mode, with the same results.
Logs from the PayTabs gateway indicate that the return handling is being skipped for the orders in question.

**Environment:**

WordPress Version: 6.4.3
PHP Version: 7.4 & 8.0
Payment Gateway: PayTabs
WooCommerce Version: 8.0.0 till 8.6.0

Other relevant environment details

Proposed Solution:
Seek assistance from PayTabs support to investigate why the return handling is being skipped for orders despite successful payments reflected in the PayTabs dashboard. Additionally, review the WooCommerce integration with PayTabs to ensure that payment status updates are being processed correctly.

Impact:
The discrepancy in payment status impacts the accuracy of order tracking and may cause confusion for both customers and administrators. It also affects the workflow of processing orders and managing inventory.

Paytabs log:
```
2024-02-15T04:28:52+00:00 PayTabs.Info: Return triggered
2024-02-15T04:28:52+00:00 PayTabs.Info: Return handling skipped for Order 91830
2024-02-15T04:35:07+00:00 PayTabs.Info: Return triggered
2024-02-15T04:35:07+00:00 PayTabs.Info: Return handling skipped for Order 91831
2024-02-15T04:52:29+00:00 PayTabs.Info: Return triggered
2024-02-15T04:52:29+00:00 PayTabs.Info: Return handling skipped for Order 91832
```

```
### WordPress Environment ###

WordPress address (URL): *************
Site address (URL): *************
WC Version: 8.6.0
REST API Version: ✔ 8.6.0
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: ✔ 6.4.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 8.2.1
OpenSSL/3.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.44-48-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.0
WC Database Prefix: yan_
Total Database Size: 5.43MB
Database Data Size: 3.65MB
Database Index Size: 1.78MB
yan_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yan_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yan_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
yan_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yan_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
yan_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yan_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yan_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yan_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yan_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
yan_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yan_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yan_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
yan_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yan_options: Data: 2.41MB + Index: 0.06MB + Engine InnoDB
yan_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
yan_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
yan_sgs_log_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yan_sgs_log_visitors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yan_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
yan_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
yan_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
yan_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yan_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
yan_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
yan_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
yan_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
yan_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yan_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yan_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yan_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
yan_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yan_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yan_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yan_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 7
post: 3
product: 18
product_variation: 7
revision: 2
shop_order_placehold: 6
wp_navigation: 1
wp_template: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

PayTabs - WooCommerce Payment Gateway: by PayTabs – 4.22.0
Speed Optimizer: by SiteGround – 7.4.6
WooCommerce: by Automattic – 8.6.0
WP Downgrade | Specific Core Version: by Reisetiger – 1.2.6

### Inactive Plugins (1) ###

Security Optimizer: by SiteGround – 1.4.11

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: SAR (ر.س)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.5.4
Author URL: https://woo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-19 10:10:04 +00:00
Options: ✔
Notes: 67
Onboarding: completed

### Action Scheduler ###

Complete: 47
Oldest: 2024-02-18 10:10:15 +0000
Newest: 2024-02-18 12:21:04 +0000

Failed: 1
Oldest: 2024-02-18 10:14:04 +0000
Newest: 2024-02-18 10:14:04 +0000

Pending: 1
Oldest: 2024-02-19 10:10:15 +0000
Newest: 2024-02-19 10:10:15 +0000


### Status report information ###

Generated at: 2024-02-18 12:39:07 +00:00

```

**Comment by wajihkm** [comment] 2024-02-19 08:23
Hi @cgdmohamed 

Kindly check your firewall settings,
Your server blocks our IPN/Callback requests.

Return skipped is normal log, it does not mean any issue, since the plugins depends on the Callback/IPN not on the Return.

Regards,
Wajih

**Comment by 5edmat** [comment] 2024-02-19 11:28
We are facing the same issue, and one of Paytabs server is connecting through HTTP port

It looks like out of all of these IPs only "********.96.147" got blocked 
That's the IP was blocked due to 30 failed attempts to connect to 1 server through the HTTP ports so they should check the details being used to connect.

Can you check that?

Thank you

**Comment by 5edmat** [comment] 2024-02-20 00:41
> Hi @cgdmohamed
> 
> Kindly check your firewall settings, Your server blocks our IPN/Callback requests.
> 
> Return skipped is normal log, it does not mean any issue, since the plugins depends on the Callback/IPN not on the Return.
> 
> Regards, Wajih

I've reviewed the case in detail and currently, The reason why the IP is being blocked is that it generates requests from a generic user-agent, that is commonly associated with malicious requests:
Go-http-client/1.1

The most optimal solution would be to use a custom user-agent, instead of this default one.

**Comment by cgdmohamed** [comment] 2024-02-20 07:20
> Hi @cgdmohamed
> 
> Kindly check your firewall settings, Your server blocks our IPN/Callback requests.
> 
> Return skipped is normal log, it does not mean any issue, since the plugins depends on the Callback/IPN not on the Return.
> 
> Regards, Wajih

Hi Wajih,

Thank you for your message and for your assistance in investigating the issue.

I wanted to inform you that our server administrator has double-checked the firewall settings, and it has been confirmed that the IPs you mentioned are not blocked. Despite this, we are still experiencing the same problem.

Additionally, I would like to update you that we have migrated to another hosting provider in an attempt to resolve the issue, but unfortunately, the problem persists.

We understand that the "skipped" log entries may be normal and not indicative of a specific issue. However, our concern lies with the failure of the IPN/Callback requests to be processed successfully, which is impacting our transaction processing.

We appreciate your continued support and any further assistance you can provide in resolving this matter.

Best regards,

**Comment by cgdmohamed** [comment] 2024-02-20 07:23
> > Hi @cgdmohamed
> > Kindly check your firewall settings, Your server blocks our IPN/Callback requests.
> > Return skipped is normal log, it does not mean any issue, since the plugins depends on the Callback/IPN not on the Return.
> > Regards, Wajih
> 
> I've reviewed the case in detail and currently, The reason why the IP is being blocked is that it generates requests from a generic user-agent, that is commonly associated with malicious requests: Go-http-client/1.1
> 
> The most optimal solution would be to use a custom user-agent, instead of this default one.

Completely agree with you.

**Comment by wajihkm** [comment] 2024-02-21 06:26
> > Hi @cgdmohamed
> > Kindly check your firewall settings, Your server blocks our IPN/Callback requests.
> > Return skipped is normal log, it does not mean any issue, since the plugins depends on the Callback/IPN not on the Return.
> > Regards, Wajih
> 
> Hi Wajih,
> 
> Thank you for your message and for your assistance in investigating the issue.
> 
> I wanted to inform you that our server administrator has double-checked the firewall settings, and it has been confirmed that the IPs you mentioned are not blocked. Despite this, we are still experiencing the same problem.
> 
> Additionally, I would like to update you that we have migrated to another hosting provider in an attempt to resolve the issue, but unfortunately, the problem persists.
> 
> We understand that the "skipped" log entries may be normal and not indicative of a specific issue. However, our concern lies with the failure of the IPN/Callback requests to be processed successfully, which is impacting our transaction processing.
> 
> We appreciate your continued support and any further assistance you can provide in resolving this matter.
> 
> Best regards,

You're welcome @cgdmohamed,

It might be a firewall settings, and it might be another protection service that cause this issue, the most common one is the Antibot that uses CAPTCHA.
If it is a CAPTCH service, Our servers consider the IPN/Callback is delivered since the response is 200.

In any case, our technical support team will be happy to check the issue in more details, kindly make sure you contact customercare@paytabs.com

Regards,
Wajih

**Comment by gangesh** [comment] 2024-02-25 19:57
@5edmat @cgdmohamed  Guys, did you managed to find the solution for this issue? 
Seems like a common one with NO solution anywhere whatsoever. 
Appreciate you help!

**Comment by cgdmohamed** [comment] 2024-02-26 13:20
> @5edmat @cgdmohamed Guys, did you managed to find the solution for this issue? Seems like a common one with NO solution anywhere whatsoever. Appreciate you help!

No, we changed to another payment gateway because technical support said we are only affected with this issue.

**Comment by gangesh** [comment] 2024-02-26 13:22
@cgdmohamed Not true. Its common issue and mainly due to client used go-htttp-client/1.1 . Thats what siteground told us. 
It was working on Wordpress.com and as soon as hosting switched, it stopped working.

**Comment by nobel0** [comment] 2024-02-26 13:47
> @cgdmohamed Not true. Its common issue and mainly due to client used go-htttp-client/1.1 . Thats what siteground told us. It was working on Wordpress.com and as soon as hosting switched, it stopped working.

Umm so i think this is because you have transferred to another hosting..
It could be solved if you uninstalled the plugin and reissue new keys if possible..

Hope it helps..

**Comment by 5edmat** [comment] 2024-02-26 13:53
> > @cgdmohamed Not true. Its common issue and mainly due to client used go-htttp-client/1.1 . Thats what siteground told us. It was working on Wordpress.com and as soon as hosting switched, it stopped working.
> 
> Umm so i think this is because you have transferred to another hosting.. It could be solved if you uninstalled the plugin and reissue new keys if possible..
> 
> Hope it helps..

uninstalling and re-installing will not solve the issue.

we have stated earlier what is the reason behind this issue.

we did not transfer/change the hosting and we are facing the same issue.

Thank you

**Comment by gangesh** [comment] 2024-02-26 14:17
> > @cgdmohamed Not true. Its common issue and mainly due to client used go-htttp-client/1.1 . Thats what siteground told us. It was working on Wordpress.com and as soon as hosting switched, it stopped working.
> 
> Umm so i think this is because you have transferred to another hosting.. It could be solved if you uninstalled the plugin and reissue new keys if possible..
> 
> Hope it helps..

Payment are being transferred, its the go-http-client/1.1 which is causing issue as per hosting. Its not safe. 
I am trying Key change anyways.

**Comment by gangesh** [comment] 2024-02-26 15:14
Same,  no solution it seems.

**Comment by cgdmohamed** [comment] 2024-02-26 16:21
As a long-standing customer for over five years, I've encountered persistent challenges with our current payment gateway. Despite efforts to address these issues, including experimenting with various hosting providers, the recurring response has been a dismissive "it is your problem."

Regrettably, after thorough consideration and weighing our options, it's become evident that it may be time to explore alternative payment gateway solutions that can better accommodate our needs and provide a more reliable service.

We value the partnership we've had thus far and appreciate the efforts made to resolve these issues. However, it's imperative for our business operations to have a payment gateway that aligns with our requirements and offers dependable performance.

**Comment by wajihkm** [comment] 2024-02-27 05:45
Sorry to hear that.

However as a workaround, you might change this line of code:
https://github.com/paytabscom/paytabs-woocommerce/blob/ed2d83f151a909df09b024cf87b0a275167a1780/includes/paytabs_payment_methods.php#L1124
Just remove `$is_ipn &&`
So after the change the code should be:
` if (!$this->pt_handled($order)) {`

You might also check this article to know why the plugin uses the `Callback` rather than the `Return`.

In the mean time, there is already a work in progress to address this case, it will be released in the next 2 weeks where the merchant can set the `user-agent` from the payment gateway's portal.

In addition to that, we might add an option in the plugin level to enable the `Return` notification to overcome such cases.

Hope that help.
Kindly let me know if this works and if there are any other concerns.

Regards,
Wajih

**Comment by gangesh** [comment] 2024-02-27 18:28
Update: IP (region specific) whitelisted on hosting account and IPN started working.

**Comment by wajihkm** [comment] 2024-03-07 05:56
@cgdmohamed @gangesh @5edmat @nobel0 
The new feature has been released in our Paytabs portal.
You can now change the IPN user-agent.
https://merchant.paytabs.com/merchant/developers/ipnconfig/agent

Regards,
Wajih

**Closed by wajihkm** 2024-03-07 05:56 UTC

**Comment by 5edmat** [comment] 2026-01-20 22:49
Dear @wajihkm,

This issue surfaced immediately after upgrading to the latest plugin release (v5.8.0). Since then, we’ve been actively engaging with your support team through multiple email threads and support tickets; however, we have not reached a viable resolution so far.

At this stage, we would like to confirm whether your team has been able to introduce an option at the plugin level to explicitly enable the Return Notification as a workaround for these scenarios.

It’s worth highlighting that selecting a random browser user agent is no longer effective with plugin version 5.8.0. This approach was operating seamlessly in the previous plugin version and did not present any issues prior to the upgrade.

Given the regression in behavior, we believe this is directly tied to changes introduced in v5.8.0, and we would appreciate clarity on whether this functionality can be reinstated or properly supported moving forward.

Thank you for your attention and support. We look forward to your guidance on the next steps.

Best regards,

**Comment by 5edmat** [comment] 2026-04-19 11:20
> > Dear [@wajihkm](https://github.com/wajihkm),
> > This issue surfaced immediately after upgrading to the latest plugin release (v5.8.0). Since then, we’ve been actively engaging with your support team through multiple email threads and support tickets; however, we have not reached a viable resolution so far.
> > At this stage, we would like to confirm whether your team has been able to introduce an option at the plugin level to explicitly enable the Return Notification as a workaround for these scenarios.
> > It’s worth highlighting that selecting a random browser user agent is no longer effective with plugin version 5.8.0. This approach was operating seamlessly in the previous plugin version and did not present any issues prior to the upgrade.
> > Given the regression in behavior, we believe this is directly tied to changes introduced in v5.8.0, and we would appreciate clarity on whether this functionality can be reinstated or properly supported moving forward.
> > Thank you for your attention and support. We look forward to your guidance on the next steps.
> > Best regards,
> 
> [@5edmat](https://github.com/5edmat)
> 
> The latest version does no changes related to IPN or Callback. Regarding the option to enable the Return option update, we will take another look into it.
> 
> Thanks

@wajihkm 
Hello dear,
we are still waiting for your feedback on the issue mentioned earlier.

Thank you
